### PR TITLE
chore: simpler error handling for windows syscalls

### PR DESCRIPTION
**Pull request by is-it-ayush**
Hey @samvdst! Here is a simpler error handling solution for windows function calls (syscalls). You don't need to manually add descriptions for codes from 0-15999, [windows-result](https://docs.rs/windows-result/0.2.0/windows_result/struct.Error.html#extended-error-info-and-the-windows_slim_errors-configuration-option) provides a wrapper around some internal error handling syscalls to give you a valid description. 

> Internally, It performs a similar process [outlined here especially step 3 and step 4](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/automat/retrieving-error-information#to-retrieve-error-information) i.e. it calls [GetErrorInfo](https://learn.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-geterrorinfo) which retrieves a pointer to an [IErrorInfo](https://learn.microsoft.com/en-us/windows/win32/api/oaidl/nn-oaidl-ierrorinfo) interface that provides the description.

I isolated this solution & tested this on a Windows Server 2022 virtual machine and it works well enough for all the codes [given here](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes#system-error-codes).
```powershell
PS C:\Users\Administrator\Downloads> .\result.exe
Error: The specified compression format is unsupported. (0x8007026A) (618)
PS C:\Users\Administrator\Downloads> .\result.exe
Error: This operation is not supported with BTT enabled. (0x800701AD) (429)
PS C:\Users\Administrator\Downloads> .\result.exe
Error: The pipe is local. (0x800700E5) (229)
PS C:\Users\Administrator\Downloads> .\result.exe
Error: This API cannot be used in the context of the caller's application type. (0x80073DE1) (15841)
```

### CODE REVIEW

**Comment by samvdst** [comment]
Hey @is-it-ayush thanks for the PR! I'm not so much concerned with getting the description for a specific error. I want an error enum so that consumers of the library can match on and take action as needed. Instead of having to match on an u32 integer code.

What I really need is to know which error codes are relevant here, but I haven't found any documentation on this.

**Comment by is-it-ayush** [comment]
Gotchu @samvdst! From multiple sources ([here](https://stackoverflow.com/a/62924318/13266368), [here](https://stackoverflow.com/a/14485797/13266368)), the answer to your question seems that there is no such list for that describes all errors thrown by a specific syscall. However, When I was looking I found the "Remarks" section of a specific syscall to be slightly helpful where they describe certain cases in which the syscall would fail along with the error code the call would throw.  For example if you look at the [remark section](https://learn.microsoft.com/en-us/windows/win32/api/virtdisk/nf-virtdisk-openvirtualdisk#remarks) for `OpenVirtualDisk`, you'll notice it throws,
- `ERROR_INVALID_PARAMETER (87)` on certain conditions.
- `ERROR_UNSUPPORTED_COMPRESSION (618)` if the host volume has been compressed.
- `ERROR_FILE_ENCRYPTED (6002)` if the host volume has been EFS encrypted after the initial virtual disk creation.
- `ERROR_FILE_SYSTEM_LIMITATION (665)` if the path is on a local network share.
- `ERROR_FILE_CORRUPT (1392)` if an ISO virtual disk is being opened and the file size is not an even multiple of 2 KB (2,048 bytes), is at least 34 KB (34,816 bytes), or the volume structure descriptor does not contain a known CDFS or UDFS volume identifier.

You can solve this problem by using my solution to handle all errors in general (that aren't documented) and then matching for special conditions given in the "Remarks" section of the syscall documentation. This way, the consumers of the library can take any action for the documented errors as they desire.

**Comment by samvdst** [comment]
> * `ERROR_INVALID_PARAMETER (87)` on certain conditions.
> * `ERROR_UNSUPPORTED_COMPRESSION (618)` if the host volume has been compressed.
> * `ERROR_FILE_ENCRYPTED (6002)` if the host volume has been EFS encrypted after the initial virtual disk creation.
> * `ERROR_FILE_SYSTEM_LIMITATION (665)` if the path is on a local network share.
> * `ERROR_FILE_CORRUPT (1392)` if an ISO virtual disk is being opened and the file size is not an even multiple of 2 KB (2,048 bytes), is at least 34 KB (34,816 bytes), or the volume structure descriptor does not contain a known CDFS or UDFS volume identifier.

Thanks for finding this! Yes, some Windows APIs are better documented than others. For example, [WNetAddConnection2A](https://learn.microsoft.com/en-us/windows/win32/api/winnetwk/nf-winnetwk-wnetaddconnection2a#return-value) lists all possible errors in the remarks section. I will add the specific errors you mentioned.

**Comment by is-it-ayush** [comment]
Np!!! I'm glad it helped. 🤞🏽

**Comment by samvdst** [comment]
> * `ERROR_INVALID_PARAMETER (87)` on certain conditions.
> * `ERROR_UNSUPPORTED_COMPRESSION (618)` if the host volume has been compressed.
> * `ERROR_FILE_ENCRYPTED (6002)` if the host volume has been EFS encrypted after the initial virtual disk creation.
> * `ERROR_FILE_SYSTEM_LIMITATION (665)` if the path is on a local network share.
> * `ERROR_FILE_CORRUPT (1392)` if an ISO virtual disk is being opened and the file size is not an even multiple of 2 KB (2,048 bytes), is at least 34 KB (34,816 bytes), or the volume structure descriptor does not contain a known CDFS or UDFS volume identifier.

Added the error messages. Going to close this. Thank you again @is-it-ayush !!

**Pull request closed without merging**
